URL = 'https://understat.com/league/EPL/2021'

OG_cols = ['Home/Away',
 'xG',
 'xGA',
 'non-penalty xG',
 'non-penalty xG Against',
 'Deep',
 'Deep Allowed',
 'scored',
 'conceded',
 'Expected Points',
 'Result',
 'date',
 'Wins',
 'Draws',
 'Loses',
 'Points',
 'Non-penalty xG difference',
 'ppda attack',
 'ppda defence',
 'ppda allowed att',
 'ppda allowed def',
 'Wins cum',
 'Loses cum',
 'Draws cum',
 'Points cum',
 'npxG difference cum',
 'xG cum',
 'xGA cum',
 'npxG cum',
 'npxGA cum',
 'scored cum',
 'conceded cum',
 'Expected Points cum',
 'Opponent',
 'Prob Win',
 'Prob Draw',
 'Prob Lose',
 'Wins in last 5',
 'Loses in last 5',
 'Draws in last 5',
 'Points in last 5',
 'npxG difference last 5',
 'xG last 5',
 'xGA last 5',
 'npxG last 5',
 'npxGA last 5',
 'scored last 5',
 'conceded last 5',
 'Expected Points last 5']

CUMSUM_LIST = ['xG', 
 'xGA', 
 'npxG', 
 'npxGA',
 'scored',
 'missed', 
 'xpts',
 'wins', 
 'draws', 
 'loses', 
 'pts',
 'npxGD']

FORM_LIST = ['xG', 
 'xGA', 
 'npxG', 
 'npxGA',
 'scored',
 'missed', 
 'xpts',
 'wins', 
 'draws', 
 'loses', 
 'pts',
 'npxGD']